# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7dcad9ea5d1cf3872c9f2b69fa7fff1fb6c6925b3ea996625573140af2d08d45154a7adf7b3bff768b1b1d3ebc948a8228c939af8f8c4cbb545c36d9e99a65

test:
  secret_key_base: 58ee94bec06e195e466a9b13005f49c713feb9fdb0f630247fc80bbbc421c12857270725bab0eb377960123da26a01627c18713848c5c6aa42ae66e26b90b432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
